
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Mar 10 19:58:50 CET 2026
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RVIGGLE = 47;
  public static final int RPARENT = 43;
  public static final int LPARENT = 42;
  public static final int LTE = 31;
  public static final int CHAR = 49;
  public static final int CONST = 3;
  public static final int CASE = 17;
  public static final int CONTINUE = 12;
  public static final int DOTCOMMA = 39;
  public static final int FOR = 18;
  public static final int MINUS = 22;
  public static final int AND = 32;
  public static final int LT = 30;
  public static final int OR = 33;
  public static final int BOOL = 50;
  public static final int COMMA = 40;
  public static final int CLASS = 5;
  public static final int INC = 35;
  public static final int DOTDOT = 38;
  public static final int DIV = 24;
  public static final int PLUS = 21;
  public static final int IF = 9;
  public static final int DOT = 41;
  public static final int ABSTRACT = 6;
  public static final int EOF = 0;
  public static final int RETURN = 13;
  public static final int EQUAL = 34;
  public static final int NEW = 19;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 23;
  public static final int NUMBER = 48;
  public static final int MOD = 25;
  public static final int NEQ = 27;
  public static final int IDENT = 51;
  public static final int BREAK = 11;
  public static final int VOID = 8;
  public static final int EQ = 26;
  public static final int GTE = 29;
  public static final int SWITCH = 16;
  public static final int ELSE = 10;
  public static final int LSQUARE = 44;
  public static final int ENUM = 4;
  public static final int READ = 14;
  public static final int RSQUARE = 45;
  public static final int EXTENDS = 7;
  public static final int QUESTION = 37;
  public static final int DEC = 36;
  public static final int GT = 28;
  public static final int PRINT = 15;
  public static final int LENGTH = 20;
  public static final int LVIGGLE = 46;
}

